image: igloo/test-runner

before_script:
  - source /etc/profile

  # Link apt cache
  - mkdir -p /cache/apt
  - rm -rf /var/cache/apt/archives
  - ln -s /cache/apt /var/cache/apt/archives

  # Link node_modules for cache
  - mkdir -p /cache/v4/node_modules /cache/v6/node_modules

  # Setup NVM dir for cache
  - mkdir -p /cache/nvm
  - export NVM_DIR=/cache/nvm

  # Install apt dependencies
  - apt-get update -qq
  - apt-get install -qq -y software-properties-common python-software-properties
  - add-apt-repository ppa:dhor/myway
  - apt-get update -qq
  - apt-get install -qq -y graphicsmagick imagemagick

node-v4:
  stage: test
  script:
    - ln -s /cache/v4/node_modules ./node_modules
    # Install node
    - nvm install v4

    # Log on private NPM
    - npm config set @igloo:registry https://npmregistry.igloo.be/
    - npm config set //npmregistry.igloo.be/:_authToken=$NPM_AUTH_TOKEN

    # Run tests
    - npm install
    - npm test

node-v6:
  stage: test
  script:
    - ln -s /cache/v6/node_modules ./node_modules
    # Install node
    - nvm install 6

    # Log on private NPM
    - npm config set @igloo:registry https://npmregistry.igloo.be/
    - npm config set //npmregistry.igloo.be/:_authToken=$NPM_AUTH_TOKEN

    # Run tests
    - npm install
    - npm test
