image: fridus/docker-rvm-nvm

before_script:
  - source /etc/profile

  # Link apt cache
  - mkdir -p /cache/apt
  - rm -rf /var/cache/apt/archives
  - ln -s /cache/apt /var/cache/apt/archives

  # Link node_modules for cache
  - mkdir -p /cache/node_modules
  - ln -s /cache/node_modules ./node_modules

  # Setup NVM dir for cache
  - mkdir -p /cache/nvm
  - export NVM_DIR=/cache/nvm

  # Install apt dependencies
  - apt-get update
  - apt-get install -y software-properties-common python-software-properties
  - add-apt-repository ppa:dhor/myway
  - apt-get update
  - apt-get install -y graphicsmagick imagemagick

node-v4:
  script:
    # Install node
    - nvm install v4

    # Log on private NPM
    - npm config set @igloo:registry https://npmregistry.igloo.be/
    - npm config set //npmregistry.igloo.be/:_authToken=$NPM_AUTH_TOKEN

    # Run tests
    - npm install
    - npm test
