image: fridus/docker-rvm-nvm

before_script:
  - source /etc/profile

  # Link node_modules for cache
  - mkdir -p /cache/node_modules
  - ln -s /cache/node_modules ./node_modules

  # Setup NVM dir for cache
  - mkdir -p /cache/nvm
  - export NVM_DIR=/cache/nvm

  # Install apt dependencies
  - apt-get update
  - apt-get install -y software-properties-common python-software-properties
  - add-apt-repository ppa:dhor/myway
  - apt-get update
  - apt-get install -y graphicsmagick imagemagick

iojs-v2:
  script:
    # Install node
    - nvm install iojs-v2

    # Set private NPM registry
    - npm set registry http://npmregistry.igloo.be/

    # Run tests
    - npm install
    - npm install -g grunt-cli
    - npm test
