language: node_js
node_js:
  - "7"
  - "8"
before_install:
  - apt-get update -qq
  - apt-get install -qq -y software-properties-common python-software-properties
  - add-apt-repository ppa:dhor/myway
  - apt-get update -qq
  - apt-get install -qq -y graphicsmagick imagemagick
