language: node_js
node_js:
  - "7"
  - "8"
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common python-software-properties
  - sudo add-apt-repository ppa:dhor/myway
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y graphicsmagick imagemagick
